DROP TABLE accueil;

CREATE TABLE accueil (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    contenu LONG,
    section VARCHAR2(20),
    
    CONSTRAINT pk_accueil PRIMARY KEY (id)
);

INSERT INTO accueil
(contenu, section)
VALUES
('INNOVER POUR FAVORISER LA PARTICIPATION SOCIALE

DES PERSONNES EN SITUATION DE HANDICAP', 'entete');